### ISSUE TITLE
gitlab docker repository name error

### ISSUE THREAD

**Issue by xueshanf** [drone/drone-cli#35] opened 2017-05-21 06:40 UTC
Gitlab docker registry supports multi-level image repo name, ie. my-group/my-project/my-image
as documented in  https://docs.gitlab.com/ce/user/project/container_registry.html 

But drone cli 0.6.0 will give an error on  multi-level repository name:
```
drone -v 
drone version 0.6.0+build.1089
drone registry add \
		--hostname gitlab.example.com \
		--repository my-group/my-project/my-image \
		--username user \
		--password @registry-key
Error: Invalid or missing repository. eg octocat/hello-world.
```

**Comment by appleboy** [comment] 2017-05-21 07:57
Your repository is the wrong format.

**Comment by bradrydzewski** [comment] 2017-05-21 09:05
duplicate of https://github.com/drone/drone/issues/2009

**Closed by bradrydzewski** 2017-05-21 09:05 UTC
