### ISSUE TITLE
drone build ls limit not working

### ISSUE THREAD

**Issue by yellowmegaman** [drone/drone-cli#75] opened 2018-01-06 20:54 UTC
Hi there!

drone server 0.8.2
drone agent 0.8.2
drone-cli 0.8.0

I've got 620 builds in repository, but drone-cli fail in trying to list them.

```
drone build ls somerepo/automation --limit 500 | grep 'Build' | wc -l
50
```
When i set limit to 10, everything works fine:
```
drone build ls somerepo/automation --limit="10" | grep 'Build' | wc -l
10
```
P.S. drone deployed with sqlite.

**Comment by bradrydzewski** [comment] 2018-01-06 21:00
the `--limit` flag is a client side limit, not server side limit. The server will always return a maximum of 50 builds because the API does not implement pagination. The intended use case for the flag is to filter the results for scripting purposes:

```
drone build start --fork octocat/hello-world \
  $(drone build ls --limit=1 octocat/hello-world)
```

Because this is working as intended, and the API does not support pagination, I am going to close this issue. If / when the API supports pagination we can implement pagination in the CLI.

**Closed by bradrydzewski** 2018-01-06 21:00 UTC

**Comment by yellowmegaman** [comment] 2018-01-06 21:06
@bradrydzewski but does it mean that we'll never be able to see (web ui/cli) more than 50 builds? 
Or maybe only by querying drone db?

**Comment by yellowmegaman** [comment] 2018-01-10 15:43
@bradrydzewski 
Maybe you can point me to repo where api is located so i can create an issue there and link it with this one? Seems strange to me to simply close the issue, if we can't view all builds.

Thanks in advance!

**Comment by bradrydzewski** [comment] 2018-01-10 16:08
we have an existing issue tracking this feature https://github.com/drone/drone/issues/1494

**Comment by yellowmegaman** [comment] 2018-01-10 16:54
Awesome. Now i can track it there, thanks!
